# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _swig_decoders
else:
    import _swig_decoders

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _swig_decoders.delete_SwigPyIterator

    def value(self):
        return _swig_decoders.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _swig_decoders.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _swig_decoders.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _swig_decoders.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _swig_decoders.SwigPyIterator_equal(self, x)

    def copy(self):
        return _swig_decoders.SwigPyIterator_copy(self)

    def next(self):
        return _swig_decoders.SwigPyIterator_next(self)

    def __next__(self):
        return _swig_decoders.SwigPyIterator___next__(self)

    def previous(self):
        return _swig_decoders.SwigPyIterator_previous(self)

    def advance(self, n):
        return _swig_decoders.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _swig_decoders.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _swig_decoders.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _swig_decoders.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _swig_decoders.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _swig_decoders.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _swig_decoders.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _swig_decoders:
_swig_decoders.SwigPyIterator_swigregister(SwigPyIterator)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _swig_decoders.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig_decoders.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _swig_decoders.DoubleVector___bool__(self)

    def __len__(self):
        return _swig_decoders.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _swig_decoders.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig_decoders.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig_decoders.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig_decoders.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig_decoders.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig_decoders.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _swig_decoders.DoubleVector_pop(self)

    def append(self, x):
        return _swig_decoders.DoubleVector_append(self, x)

    def empty(self):
        return _swig_decoders.DoubleVector_empty(self)

    def size(self):
        return _swig_decoders.DoubleVector_size(self)

    def swap(self, v):
        return _swig_decoders.DoubleVector_swap(self, v)

    def begin(self):
        return _swig_decoders.DoubleVector_begin(self)

    def end(self):
        return _swig_decoders.DoubleVector_end(self)

    def rbegin(self):
        return _swig_decoders.DoubleVector_rbegin(self)

    def rend(self):
        return _swig_decoders.DoubleVector_rend(self)

    def clear(self):
        return _swig_decoders.DoubleVector_clear(self)

    def get_allocator(self):
        return _swig_decoders.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _swig_decoders.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _swig_decoders.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _swig_decoders.DoubleVector_swiginit(self, _swig_decoders.new_DoubleVector(*args))

    def push_back(self, x):
        return _swig_decoders.DoubleVector_push_back(self, x)

    def front(self):
        return _swig_decoders.DoubleVector_front(self)

    def back(self):
        return _swig_decoders.DoubleVector_back(self)

    def assign(self, n, x):
        return _swig_decoders.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _swig_decoders.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _swig_decoders.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _swig_decoders.DoubleVector_reserve(self, n)

    def capacity(self):
        return _swig_decoders.DoubleVector_capacity(self)
    __swig_destroy__ = _swig_decoders.delete_DoubleVector

# Register DoubleVector in _swig_decoders:
_swig_decoders.DoubleVector_swigregister(DoubleVector)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _swig_decoders.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig_decoders.StringVector___nonzero__(self)

    def __bool__(self):
        return _swig_decoders.StringVector___bool__(self)

    def __len__(self):
        return _swig_decoders.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _swig_decoders.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig_decoders.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig_decoders.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig_decoders.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig_decoders.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig_decoders.StringVector___setitem__(self, *args)

    def pop(self):
        return _swig_decoders.StringVector_pop(self)

    def append(self, x):
        return _swig_decoders.StringVector_append(self, x)

    def empty(self):
        return _swig_decoders.StringVector_empty(self)

    def size(self):
        return _swig_decoders.StringVector_size(self)

    def swap(self, v):
        return _swig_decoders.StringVector_swap(self, v)

    def begin(self):
        return _swig_decoders.StringVector_begin(self)

    def end(self):
        return _swig_decoders.StringVector_end(self)

    def rbegin(self):
        return _swig_decoders.StringVector_rbegin(self)

    def rend(self):
        return _swig_decoders.StringVector_rend(self)

    def clear(self):
        return _swig_decoders.StringVector_clear(self)

    def get_allocator(self):
        return _swig_decoders.StringVector_get_allocator(self)

    def pop_back(self):
        return _swig_decoders.StringVector_pop_back(self)

    def erase(self, *args):
        return _swig_decoders.StringVector_erase(self, *args)

    def __init__(self, *args):
        _swig_decoders.StringVector_swiginit(self, _swig_decoders.new_StringVector(*args))

    def push_back(self, x):
        return _swig_decoders.StringVector_push_back(self, x)

    def front(self):
        return _swig_decoders.StringVector_front(self)

    def back(self):
        return _swig_decoders.StringVector_back(self)

    def assign(self, n, x):
        return _swig_decoders.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _swig_decoders.StringVector_resize(self, *args)

    def insert(self, *args):
        return _swig_decoders.StringVector_insert(self, *args)

    def reserve(self, n):
        return _swig_decoders.StringVector_reserve(self, n)

    def capacity(self):
        return _swig_decoders.StringVector_capacity(self)
    __swig_destroy__ = _swig_decoders.delete_StringVector

# Register StringVector in _swig_decoders:
_swig_decoders.StringVector_swigregister(StringVector)
class VectorOfStructVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _swig_decoders.VectorOfStructVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig_decoders.VectorOfStructVector___nonzero__(self)

    def __bool__(self):
        return _swig_decoders.VectorOfStructVector___bool__(self)

    def __len__(self):
        return _swig_decoders.VectorOfStructVector___len__(self)

    def __getslice__(self, i, j):
        return _swig_decoders.VectorOfStructVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig_decoders.VectorOfStructVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig_decoders.VectorOfStructVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig_decoders.VectorOfStructVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig_decoders.VectorOfStructVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig_decoders.VectorOfStructVector___setitem__(self, *args)

    def pop(self):
        return _swig_decoders.VectorOfStructVector_pop(self)

    def append(self, x):
        return _swig_decoders.VectorOfStructVector_append(self, x)

    def empty(self):
        return _swig_decoders.VectorOfStructVector_empty(self)

    def size(self):
        return _swig_decoders.VectorOfStructVector_size(self)

    def swap(self, v):
        return _swig_decoders.VectorOfStructVector_swap(self, v)

    def begin(self):
        return _swig_decoders.VectorOfStructVector_begin(self)

    def end(self):
        return _swig_decoders.VectorOfStructVector_end(self)

    def rbegin(self):
        return _swig_decoders.VectorOfStructVector_rbegin(self)

    def rend(self):
        return _swig_decoders.VectorOfStructVector_rend(self)

    def clear(self):
        return _swig_decoders.VectorOfStructVector_clear(self)

    def get_allocator(self):
        return _swig_decoders.VectorOfStructVector_get_allocator(self)

    def pop_back(self):
        return _swig_decoders.VectorOfStructVector_pop_back(self)

    def erase(self, *args):
        return _swig_decoders.VectorOfStructVector_erase(self, *args)

    def __init__(self, *args):
        _swig_decoders.VectorOfStructVector_swiginit(self, _swig_decoders.new_VectorOfStructVector(*args))

    def push_back(self, x):
        return _swig_decoders.VectorOfStructVector_push_back(self, x)

    def front(self):
        return _swig_decoders.VectorOfStructVector_front(self)

    def back(self):
        return _swig_decoders.VectorOfStructVector_back(self)

    def assign(self, n, x):
        return _swig_decoders.VectorOfStructVector_assign(self, n, x)

    def resize(self, *args):
        return _swig_decoders.VectorOfStructVector_resize(self, *args)

    def insert(self, *args):
        return _swig_decoders.VectorOfStructVector_insert(self, *args)

    def reserve(self, n):
        return _swig_decoders.VectorOfStructVector_reserve(self, n)

    def capacity(self):
        return _swig_decoders.VectorOfStructVector_capacity(self)
    __swig_destroy__ = _swig_decoders.delete_VectorOfStructVector

# Register VectorOfStructVector in _swig_decoders:
_swig_decoders.VectorOfStructVector_swigregister(VectorOfStructVector)

def ctc_greedy_decoder(probs_seq, vocabulary):
    return _swig_decoders.ctc_greedy_decoder(probs_seq, vocabulary)

